export enum routes {
  DASHBOARD = '/dashboard',
  TYPOGRAPHY = '/typography',
  TABLES = '/tables',
  NOTIFICATION = '/notification',
  UI_ELEMENTS_ICONS = '/ui/icons',
  UI_ELEMENTS_CHARTS = '/ui/charts',
  UI_ELEMENTS_MAP = '/ui/map',
  LOGIN = '/login',
  CADASTRO_MEDICO_LISTA = '/cadastro/medico/lista',
  CADASTRO_MEDICO_PROFILE = '/cadastro/medico/profile',
  CADASTRO_PACIENTE_LISTA = '/cadastro/paciente/lista',
  CADASTRO_PACIENTE_PROFILE = '/cadastro/paciente/profile',
  TRIAGEM = '/triagem',
  FILA = '/fila/components',
}
