export interface ProntuarioModel {
    id: string,
    nome: string,
    dataNascimento: Date,
    genero: number,
    cpf: string,
    status: number,
    queixa: string,
    pa: string, 
    fc: string,
    fr: string,
    sintomaResp: string,
    sp: string,
    temperatura: string,
    doencasSistemicas: string,
    locomocao:number,
    dataAtendimento: Date,
    ativo: boolean

    diagnostico: string,
    sintomas: string,
    doencaAtual: string,
    doencaPregressa: string,
    cirurgia: string,
    medicacao: string,
    testes: string,
    alergias: string,
    evolucao: string,
}